name: hourly_focus
description: A productivity tracking app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <=3.7.2"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3 # SQLite database
  syncfusion_flutter_charts: ^28.2.12
  flutter_local_notifications: ^17.2.2 # Notifications (disabled for now)
  path: ^1.8.3 # File path handling
  timezone: ^0.9.2 # Timezone support for notifications
  speech_to_text: ^6.6.0 # Voice input for notes
  permission_handler: ^11.3.1 # Microphone permissions
  csv: ^6.0.0 # CSV generation
  share_plus: ^7.2.2 # File sharing
  path_provider: ^2.1.4 # Temporary file storage
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
